### ISSUE TITLE
Petition for nallar to accept a maintainer

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#1016]
As we all know this system that nallar has created is beast! it basically allows us to do things that weren't possible before and im very grateful for the time you have put into this! But there is an issue about what happens now with it, I personally think and hope that nallar would be willing for us to find a suitable maintainer to look after the system whilst nallar is having a break/stopped making the system.

If you guys agree please also write  "I agree"

**Comment by HaoSs07** [comment]
nallar, Aug 15, 2013

Anyone else is free to continue working on this - the license is very permissive. If you need builds done I can also point the build server at your github, assuming anyone does continue working on it.

http://forum.feed-the-beast.com/threads/tickthreading-concurrent-entity-tile-entity-ticks-and-other-optimisations.6498/page-38#post-395800

**Comment by LunNova** [comment]
The issue is that no-one else wants to do it, not that I'm not letting them! :P

**Comment by HaoSs07** [comment]
well i had some discussions with some dev friends. the amount of work hours and knowledge is beyond them, they ware impressed :)) u should work at mojang. implementing this for mc

**Comment by dariusc93** [comment]
I do small minor patches to TT, but nothing that should be release to public since its experimental and its for something im working on, as well as to attempt to patch the stupid spam I get from ME/AE -_-. We rely on TT, but since Nallar is in for a break and 1.6 is around the corner, we are working on something to help with that. Hopefully things work well..

Minecraft itself isnt really made to be in a multi-threaded environment, HaoSs07, but some work stuff can be done to how TT has it.
