### ISSUE TITLE
A proposal

### ISSUE THREAD

**Issue by BlackAce21** [MinimallyCorrect/TickThreading#1051]
I noticed on your latest notes that you are having trouble with the prepatcher, I have browsed your code a bit and I understand a bit about what it is your trying to do. Would it not be easier to rewrite the base minecraft files directly instead of trying to wrap them? Essentially multithread minecraft at the core and just repackage it. As long as the methods return the same values and are in the same place it shouldnt even effect forge based mods yes? I am not the most exp. java programmer in the world but it is a project I would like to see turned into reality and would even be willing to help with if I could, even if its just another set of eyes to catch the small things here and there. Multithreading is important to a lot of people, whatever I can do to help I would be happy to do so.

**Comment by ruifung** [comment]
In which case, mods which access said files directly would break. Some mods patch minecraft directly too, and the large amount of changes required for multithreading would break all those mods. Or so I think anyway.

**Comment by LunNova** [comment]
The prepatcher is needed so that if I patch a base class to add a method/field to it, my other classes can access that method/field normally.

For example, see https://github.com/nallar/TickThreading/blob/master/src/common/nallar/patched/PatchTileEntity.java - lots of methods and fields are added to TileEntity from that class. In other classes, for example: https://github.com/nallar/TickThreading/blob/master/src/common/nallar/tickthreading/minecraft/tickregion/TileEntityTickRegion.java#L35 these methods/fields are then accessible in TileEntity instances.

**Comment by BlackAce21** [comment]
I understand the theory behind the prepatcher but shouldn't you theoretically be able to add methods and tweak existing ones within the base code so long as the methods still return the expected results or do their expected tasks without breaking mods? At the core the problem lies within the sheer amount of block updates being processed on a single thread, if you were to dynamically thread pool those tasks in the base code and package it as a modified version of Forge (sort of like how MCPC adds spigot) wouldn't that work and be a much simpler solution? I am amateur at this but I am going to school for it so I am eager to understand as much as possible.
