### ISSUE TITLE
Opis not working no errors no messages at all - Also a feature request

### ISSUE THREAD

**Issue by Katelyn-SN** [MinimallyCorrect/TickThreading#1077]
when running opis it does its 250 ticks then stops but in the application no tick times are showing like it profiled nothing test for yourself as my servers print no errors when this occured. Its working fine without TT installed

Feature Request:

Also Opis does its own neat thing with a separate window for manangement of the mod maybe you can do that nallar for changes on the fly and profiling results displayed right there. Instead of having to look at a text dump.

Like this:

![image](https://cloud.githubusercontent.com/assets/2229748/2898373/eb61e67a-d59b-11e3-8e17-2bb43dde7705.png)

**Comment by Dark-Arcana** [comment]
Test with forge without MCPC+ to see if there are any interactions that might be causing this issue.

Java swing isn't the most fun thing to work with. If you would like to implement it, go ahead, but instead I personally would think that priorities could be focused elsewhere.

**Comment by Katelyn-SN** [comment]
This is more of a after thought for some extra features and not something to be done asap

**Comment by LunNova** [comment]
Opis probably won't ever work correctly with TT - the profiling isn't designed to handle multi-threaded entity ticks, and since it's designed to measure timings it needs a bit of a rewrite to work with TT.

It'd be easier just to improve TT's profiling to have an interface similar to Opis than to patch Opis to work, given that much of Opis' design for profiling this stuff just doesn't make sense under TT.

I've made an issue for adding those features to TT: #1081
