### ISSUE TITLE
Trees aren't growing

### ISSUE THREAD

**Issue by Daniel86268** [MinimallyCorrect/TickThreading#1087]
Seems that all Trees are affected. Bonemeal isn't working either, particles are showing up and the sapling consumes bonemeal, but the tree just doesn't grow.

**Comment by LunNova** [comment]
Are you using MCPC+? Can you link your patcher log?

**Comment by Daniel86268** [comment]
https://gist.github.com/Daniel86268/ff4146a410694015d639

**Comment by Katelyn-SN** [comment]
Issue confirmed with MCPC+ no console errors just unlimited amounts of bone meal wont grow a tree

**Comment by Katelyn-SN** [comment]
Tested this build i see no debugging for it...

**Comment by Katelyn-SN** [comment]
I see this 

```
05-17 19:09:14 [FINE] [TTPatcher] Patching net.minecraft.block.BlockSapling with threadLocalBoolean(field:captureTreeGeneration,threadLocalField:$0.inCaptureTreeGeneration)
```

That is all

**Comment by LunNova** [comment]
If the issue was that the MCPC+ tree generation capture code was still using the old fields I didn't want it to use, this would have made it crash instead of just doing nothing, while also making it obvious what the problem is.

Unfortunately that wasn't the issue, so it changed nothing. Now to try to figure out what else could be broken.

**Comment by witchway915** [comment]
I found that Forestry Fertilizer (ID 31976) is a decent workaround at the moment and can be applied similarly to bone meal
