### ISSUE TITLE
Improvements to MCs Fly Detection?

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#109]
As you know, MC Kicks players who are "flying" after some time.

The problem is, people can fly in short bursts without ever being detected by this vanilla system - making the check pretty useless.

I'd like to see a system similar to NoCheatPlus implementation of "rolling" the person back to the ground when caught with a flying violation and the like.

**Comment by Puremin0rez** [comment]
I should note I obviously mean flying with hacks, not with items etc.

**Comment by Sp0nge** [comment]
I think nallar is working on something similar, to combat those clients out there that cheats :)

**Comment by ghost** [comment]
Sort of back tracking on this ticket, but I get kicked sometimes if I use a Gravisuit. I find that using boost or a lag spike increases the chances of being kicked. Is there some way to add a check so that if the player is wearing certain items like that, they are ignored by fly checking?

**Comment by tprussak** [comment]
Forge on it's own breaks most flyhacks simply by being incompatible. And vanilla fly-detection is almost always off on forge servers that have a mod that allows legitimate flight, as vanilla fly detection indiscriminately kicks players who are in the air for long enough and not in creative. I've even been kicked for using a player-launching TNT cannon once on a vanilla server, simply because I was in the air for too long.

**Comment by LunNova** [comment]
Not going to implement this as part of TT. With MCPC+, other anti-cheat solutions are available.
