### ISSUE TITLE
How is it working

### ISSUE THREAD

**Issue by gunnar19991** [MinimallyCorrect/TickThreading#1091]
How do you use the new TT is it placed into the mods folder or is it left out in the main directory named TT.jar or do you launch it like a forge jar for you server with a bat file?

**Comment by ghost** [comment]
https://github.com/nallar/TickThreading/blob/master/INSTALL.md

Its not ready for public servers yet.

**Comment by Katelyn-SN** [comment]
No support will be provided for unstable builds, Also this is a message for anyone trying to setup unstable builds of TickThreading on public servers.

You should NOT be using it for any server unless aiding in development in a way that is of benefit of more than just you or your server. Under no circumstances will the community be obligated to provide support for unstable builds, if you are not able to install them or read basic instructions you should not be using this in the first place. No support or compensation will be given for negative effects caused by the TickThreading mod if there is any as there is no way to make it completely stable and support all mods that are released.

Hope this clears up any confusion about this mod during its development period I'm sure nallar will make a public announcement when TickThreading is stable enough for general purpose servers to use.
