### ISSUE TITLE
Forestry Carpenters cause client crash

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#12]
This doesn't happen without TickThreading

Reproduce:
Run MindCrack v6 server WITHOUT TickThreading
Spawn Carpenter
Place Carpenter
Attempt to open it - it should work fine

Run MindCrack v6 Server WITH TickThreading
Spawn Carpenter
Place Carpenter
Attempt to open it - you will crash immediately.

You also cannot craft the item with TickThreading enabled, it doesn't let you take it from the crafting square.

Here is the client crash
# 

java.lang.ClassCastException: forestry.factory.gadgets.MachineCarpenter cannot be cast to forestry.factory.gadgets.MachineFermenter
    at forestry.factory.gui.GuiFermenter.drawGuiContainerBackgroundLayer(GuiFermenter.java:29)
    at forestry.core.gui.GuiForestry.a(GuiForestry.java:231)
    at ban.b(EntityRenderer.java:1150)
    at net.minecraft.client.Minecraft.J(Minecraft.java:882)
    at net.minecraft.client.Minecraft.run(Minecraft.java:771)
#     at java.lang.Thread.run(Unknown Source)

**Comment by LunNova** [comment]
I'm guessing you didn't see due to the console spam from advanced machines/IC2, but the server console shows `2013-01-07 17:49:36 [INFO] [ForgeModLoader] Encountered a class forestry.core.gadgets.TileMachine with meta 5. However no such MachinePackage exists. Falling back to meta=0.` when this happens.

Should have it fixed soon :)
