### ISSUE TITLE
REMOVED BY REQUEST OF THE INTERNET TROLL TF101-WIZARD!

### ISSUE THREAD

**Issue by Zilacon** [MinimallyCorrect/TickThreading#1228]
REMOVED BY REQUEST OF THE INTERNET TROLL TF101-WIZARD!

**Comment by ghost** [comment]
Obviously no one is silly enough to run it on a public server yet, just stop using Tick Threading until Nallar has time to fix some issues.

**Comment by GUIpsp** [comment]
> Obviously no one is silly enough to run it on a public server yet

HA

**Comment by Zilacon** [comment]
REMOVED BY REQUEST OF THE INTERNET TROLL TF101-WIZARD!

**Comment by Katelyn-SN** [comment]
It's quite simple if you intend to use these on public servers know the consequences i use them on public servers only after extreme testing and deemed them safe for only certain packs, any simple bugs i found i fixed if you don't have any experience with the way this mod works you should really not be using it at all at this point.

I speak from my mild experience with this mod and the code behind it im no expert either but it's quite simple to say "Don't Use It On Public Servers Yet!". Also Post errors that nallar can actually fix the little information you gave was not sufficient to benefit nallar in fixing it.

**Comment by Zilacon** [comment]
REMOVED BY REQUEST OF THE INTERNET TROLL TF101-WIZARD!

**Comment by Katelyn-SN** [comment]
I've seen these types of errors before there are ways to make them more verbose if you had the experience that you really should have to be using a mod in a development condition you would know that all messages that are in a HRF aka Human Readable Format have a non HRF dump most of the time either as a stack trace or a hex dump for more severe cases that simply need to be dumped using some simple code. Also I don't simply "troll" github like the way you describe, and seeing as some of the words that you used to describe my actions your just about as incompetent as a user that doesn't know how to install a mod let alone use one in a development stage. If you want a problem solved you need to do a little more work on your own and not going "Oh that's an error that is unexplainable, ticket!"  Much more could be done on your end to be of more of a benefit. Also if your servers crash so much maybe its time for a hardware upgrade or maybe a bit more effort in patching to correct the issues? Rather than install a mod to make the quite clear apparent issues less apparent?

**Comment by Zilacon** [comment]
REMOVED BY REQUEST OF THE INTERNET TROLL TF101-WIZARD!

**Comment by Katelyn-SN** [comment]
Great servers huh you spend all that but yet you cannot spend decent money each money on a website that actually stays on-line Pfft and Also you spend all that but yet you cannot spend decent money each money on a website that actually stays on-line Pfft and Also you think you can basicly tell a persons financial situation based on how they speak. Quite the feat i might say or as you might say "ARYEJESUS" The oil fields up here are great to us, That's all you really need to know considering how ungreatful you are for the money you supposedly have.

This conversation really has to stop in fact its way out of topic nor does it make any reason to be here the moral is don't use it until such time as you can actually use it without major errors.

Seeing as nallar is like popping up here and there doing very minor stuff my guess is he's not going to work it for a while again and im sure this ticket quite helped his thoughts on that. Simply don't expect a fix soon from him maybe try and do it yourself

**Comment by Zilacon** [comment]
You know what your almighty majesty? I will end it right here, because YOUR NOT!
You have continued to post and argue with me insult me and my servers for several hours.

You want this ticket gone, its gone.
