### ISSUE TITLE
TT completely uncompatible with CauldronLegacy

### ISSUE THREAD

**Issue by Zilacon** [MinimallyCorrect/TickThreading#1229]
So MCPC is now called Cauldron and they are now using Gradle and have a installer now to download the libraries and a jar file to run afterwards...

I tried running this and TT is completely screwed when trying to run it on this (I suspected that before running it) so back to the old MCPC until some fixes are thrown out there for this.

**Comment by Katelyn-SN** [comment]
You can get it work but you need to run the installer which does not work on linux because it's a gui so i ran it on my pc and zipped up the libraries folder for your testing you can get it here: 

https://drive.google.com/file/d/0B_ezGwB4rZiNakdEM3Q4a1FUVm8/edit?usp=sharing

Then you can launch the cauldron-1.6.4-1.965.7-Bx.jar from TickThreading it will run but it has a few errors so i included my server log here: For nallar to do some debugging http://hastebin.com/rivolipoyo.vbs

Seems they moved or deleted alot of the things that nallar patched so im not sure how well he will be able to make it work but the server did start. So for now i suggest using the latest mcpc+ build from here: http://ci.md-5.net/job/Cauldron-164/ which according to the commits has no major changes done that would affect you greatly.

**Comment by nylser** [comment]
You can also run the installer on the server with `java -jar the_installer.jar --installServer`

**Comment by Zilacon** [comment]
Nylser... I explained in my original post i used the installer...
The build of cauldron itself is not compatible with TT because TT was never built to work with this build of Cauldron.

**Comment by bloodmc** [comment]
@Zilacon gradle server? what are you talking about? gradle is used to BUILD the software, it has NOTHING to do with the server once it is built.

nallar just has to update his patches to work with latest changes that I did in cauldron.
As for the installer not working on linux, this is false as well...The installer is identical to forge and can simply be run by using the command that nylser posted above.

**Comment by Katelyn-SN** [comment]
Here's a better question @bloodmc Is there any SIGNIFICATE changes in this new cauldron compared to the mcpc-plus builds that would be worth upgrading for? This would state whether or not this ticket is even relevant at this point in time.

**Comment by bloodmc** [comment]
@tf101-wizard many significate changes and bug fixes. Read the changelog to see them all.

**Comment by Katelyn-SN** [comment]
Only asking since I haven't made the switch yet but have did enough patches to make TT not throw so many bugs due to missing or moved classes

**Comment by Dark-Arcana** [comment]
Dude kevhawk. Like what. I don't even. Came here for a good laugh though.

Seriously if anyone is concerned about anything, just read what @bloodmc has said.

**Comment by Zilacon** [comment]
@bloodmc I am aware gradle is the software to build the program but MCPC was not built with gradle until now according to your release notes! I am reading off WHAT YOU SAID in your build comments!

**Comment by Katelyn-SN** [comment]
It makes no difference gradle in no way effects how it works or operates it has no effect on anything saying this would be the cause of some of the errors is incorrect.

**Comment by Dark-Arcana** [comment]
You can't build something off of gradle. lel. Gradle is just a scripting language that takes input commands that do a certain thing in a certain order. Essentially, it builds a thing like making a recipe. Cauldron is not built off of gradle. Look shit up before you start yelling at people.

**Comment by Zilacon** [comment]
The internetz trolls are strong with these ones...

You wanna talk about yelling at people @Dark-Arcana ? The one who spent hours bitching at mojang about technics launcher? You are not one to talk about bitching at people, you are in fact a prime example of bitching at people.

**Comment by Dark-Arcana** [comment]
You might be overstepping yourself a little bit here Zilacon. I've had many in depth conversations with Mojang employees, and many of those conversations were pretty good. If you are referring to that reddit post that Asie made public, that wasn't my doing. It also wasn't an argument so much as a discussion, but minecrafters on Reddit like to make everything into drama. It snowballs really fast. Yeah, some of us in the Technic crowd were a little upset, but we talked it over like adults and we settled everything down.

Thing is, who the fuck are you to say anything to me? Get your facts straight before you step up.

@nallar You may want to close/lock this before it gets out of hand.

**Comment by Katelyn-SN** [comment]
This argument seems to be completely irrelevant just quit it seriously every single person on the internet is a "troll" and even that statement is a little misguided you both should go your separate ways as your doing no more than making fools out of yourselves.

**Comment by Zilacon** [comment]
@Dark-Arcana Ill do it myself, whenever @tf101-wizard posts on any of my issues on TT it starts to get out of hand even when he himself was wrong as stated by @bloodmc in his own reply to my issue report.

I had no issues with my installer on linux FYI @tf101-wizard your just a horrible troll who loves to stir shit up in anything i post.

**Comment by Zilacon** [comment]
Closing this issue so i don't get anymore spam emails from this pointless argument over nothing.

**Comment by Dark-Arcana** [comment]
To be fair @Zilacon, @tf101-wizard is usually wrong about almost everything. That's not me being mean, but he argues with me just about all of the time and is usually shut down by an audience of people telling him he has no idea what he's talking about. He still believes he's correct though. He's one of those special cases where his parents have given him everything and told him he's special his whole life so he blinding presses on with an over inflated sense of entitlement. But yeah, good idea to close this. Thanks ;)

**Comment by Zilacon** [comment]
@Dark-Arcana No problem. I deal with enough drama in my own community, fighting about a misunderstanding about gradle on my part is not something i want to waste my time on.

I'll tell you right now, as i tell everyone who speaks to me on my teamspeak. I am no genius, i do not program java, and i do not have a vast experience in anything related to java. I do however know several web design languages to make websites, photoshop, operating system knowledge, hard ware and software knowledge etc. And i manage my own dedicated custom built MC servers.

I posted a bunch of things in one post before and nallar told me to make a seperate issue report for anything i found wrong with TT big or small, that's what im doing. When i discover an issue i let the developer know about it so it can possibly help in a future fix.

I got my own programmers on my servers but i got them focused on our own custom made plugins and i don't want them splitting their workload so that they cant get any playtime in and actually finish stuff lol.

**Comment by Dark-Arcana** [comment]
@Zilacon you're definitely doing it the right way. Sometimes you make a post about something that isn't an actual bug/issue based on your ignorance of a subject. We all do it from time to time because there are just so many things. Just keep doing that and when Nallar is back from break, he can look into things.

**Comment by Katelyn-SN** [comment]
@Zilacon @Dark-Arcana Its as simple as this we are no better than anyone here. This cause big or small is cause of a group action and not of 1 person. @Dark-Arcana  The things you talk about are not always up to par either but does anyone bother to contradict you ? No. @Zilacon You do all this work with these servers and you simply state you don't know everything. But you know alot its the same from my stand point i know alot of things. With the development and setup of servers i don't know it all nor do i always know things relevant to the task at hand. What I'm getting on with is nobody here is in the right and nobody knows everything. Its no wonder @nallar Doesn't work on his project more because there is a bunch of blubbering fools that includings me @Zilacon @Dark-Arcana destroying his community.

We all need to step back and look at is this as is it relevant to the mod? No then we shouldn't do it. 

At the end of the day Tangents waist time work solves issues.

**Comment by Zilacon** [comment]
@tf101-wizard Are you stoned or some shit?

There is so many contradictions in that single post that i am confused as hell just reading it!

You talk about @nallar not working on this project because of people like me reporting issues? @nallar has a fucking life dude, like many other people. This project (TickThreading) is a HOBBY, it is not his job, no one is paying him hourly to work on this. He is taking time out of his life to work on this for the benefit of others.

Just do us all a damn favor and stfu!

**Comment by Katelyn-SN** [comment]
Maybe you should read and understand its not about the posting issues. You do a alright job of that and it helps but im sure that nallar is less likely to even bother coming back to this with all this crap going on and it isn't just me.

**Comment by Zilacon** [comment]
@tf101-wizard Please point at every issue report that has "crap" going on. Please take a good hard look at every single issue that has arguments on it.

ITS YOU! ALWAYS YOU!
AND THIS RIGHT HERE IS PROOF ITS YOU!
I CLOSED THIS SHIT AND YOUR STILL ARGUING!

**Comment by alicheek** [comment]
Guys it's early in the morning and my phone is buzzing like mad, let's just all stop posing and get some tea and chill out 😁

**Comment by NGSilentshots** [comment]
BITCH I DONT DRINK TEA! SLEEP IS FOR THE WEAK!

**Comment by SkyyFox** [comment]
Here in 'murica unless its beer or nascar , not 1 fuck will be given.... same goes for this "tea" You could also try this thing called turning your phone off... should think about that while you sip your tea

**Comment by Zilacon** [comment]
@NGSilentshots , @SkyyFox ... I... WHAT!?

I am literally going to yell at github right now about what a CLOSED ISSUE means, like i dont know... CLOSED? NO MORE REPLIES? LOGIC?

Where is Spock to explain peoples broken logic when you need him...

Either way, unsubscribing from this issue ive had enough.

**Comment by SkyyFox** [comment]
@Zilacon github is like a woman.... you may scream and yell at her all you want , hell you may even close her out with an "end of discussion" but youre not allowed to leave... itll always come back ....even if its closed...

**Comment by alicheek** [comment]
Nice, really shows the maturity of you doesn't it, easier thing yet so I actually get important notifications and not these just unsubscribe to the thread 😉 , but thank you for your masterfully enlightened knowledge sir your a credit to your country...

Thanks

Alistair Cheek

Owner of Brierie Servers

**Comment by SkyyFox** [comment]
@alicheek

**Comment by SkyyFox** [comment]
@alicheek oh im sorry , did i just re-subscribe you to this topic that you unsubscribed from? HUH , maybe this tea is getting to me... also , i take offense you assume im a sir - thank you for calling me of the male gender.... Now , who's the real mature one here?

**Comment by Dark-Arcana** [comment]
My god. This whole post is pure gold now. Bring your fuckin' popcorn. @tf101-wizard what on Earth are you even talking about?

@tf101-wizard First off, why don't you try to point out a situation where my information wasn't up to par and how I acted about it. Unlike a child (referencing you here) and more like the scientist that I am, I take on new information and update my view of the world as is necessary. If it isn't relevant or important, then it should be discarded. So like a scientist, I relish in being wrong as I can learn something new and improve upon myself. Point out where I'm wrong please.

@Zilacon was doing something very similar (and you are getting emails because your name is being referenced like this even if your unsubscribed or closed the topic). He doesn't have to know everything or prove it to anyone else in some immature way.

Nallar says he hasn't even opened the Minecraft client in over a year and a half. His development of TickThreading is seriously just a hobby and for the progression of his programming skills. He has no obligation to make further improvements or patches. No one else does either. Nallar isn't going to quit because some randoms on the internet are crying over something or having an argument. That view of the world is.. I don't really understand where you are coming from with that. If Nallar stops or has already stopped working on this again, it will be because he has a life, he has other things that are a higher priority, and he has moved on from Minecraft. If you have an issue with TickThreading, fork it and patch it yourself. Then you can have all of the features you want and leave everyone alone. Because as @Zilacon has pointed out already, most of the drama stems directly from you @tf101-wizard. As far as tangents go, it's important to discuss when a member of the community is bringing down the rest of the community. A lot of people complained about you in IRC. And there are people complaining about you here. Like a moderator for a server, any community is self moderating (yes I will explain this to you like a child). I don't have the power to remove you from github, but if you start anything else, you will be banned from the IRC channel. Enough is enough.
