### ISSUE TITLE
[1.12.2] Crash on launch

### ISSUE THREAD

**Issue by Fatmice** [MinimallyCorrect/TickThreading#1265]
Nothing but 
minecraft_server.1.12.2
forge-1.12.2-14.23.0.2529
spongeforge-1.12.2-2529-7.0.0-BETA-2729
TickThreading-1.12.3-extended

Crash log
[fml-server-latest.log](https://github.com/MinimallyCorrect/TickThreading/files/1455942/fml-server-latest.log)

**Comment by CappyT** [comment]
Did you read the "not yet functional" on the main page?

**Comment by Fatmice** [comment]
Are you a troll or something?  Shoo

**Comment by LunNova** [comment]
It's unfinished and isn't expected to work. He's not a troll.

**Comment by Fatmice** [comment]
I'm well aware of that, just wanted to see where it will fail...This thread is how many months old now and he just suddenly show up to "inform" me of that?  If that is not trolling then what?

**Comment by LunNova** [comment]
Sorry @Fatmice. Didn't notice the timestamp.

The current jenkins "-core" builds should launch and the server may work, but they don't do anything useful. A few very minor tweaks. Not much point in testing it.

The "-extended" build is completely broken as it has multiple partially implemented patches for threading, including methods which `throw new UnsupportedOperationException()` because they've not been written yet.
