### ISSUE TITLE
Patcher isn't Patching

### ISSUE THREAD

**Issue by tubaboy26** [MinimallyCorrect/TickThreading#169]
02-21 18:37:28 [INFO] [TickThreading] Running TickThreading v1.0.0.970 for MC1.4
.7
02-21 18:37:29 [SEVERE] [TickThreading] Can't patch - no backup for ftbserver.ja
r exists, and a patched copy is already in the mods directory.
02-21 18:37:29 [SEVERE] [TickThreading] An error occurred while patching, can't
continue
java.lang.Error: Missing backup for patched file
        at me.nallar.tickthreading.patcher.ClassRegistry.restoreBackups(ClassReg
istry.java:364)
        at me.nallar.tickthreading.patcher.PatchManager.loadBackups(PatchManager
.java:67)
        at me.nallar.tickthreading.patcher.PatchMain.patcher(PatchMain.java:92)
        at me.nallar.tickthreading.patcher.PatchMain.main(PatchMain.java:31)
02-21 18:37:29 [INFO] [TickThreading] Done. Press enter to exit.

My Tickthreading backups folder is empty and so is patchedMods. As far as I can figure out this is why. Don't know what to do though...

**Comment by HaoSs07** [comment]
because you have a patched ftbserver.jar but no backup of a clean one to repatch. replace current one with a clean ftbserver.jar .
When you patch it makes backups for all mods, when you repatch. it uses the clean mods from backup to overwrite the current patched ones. so you always patch clean mods. not repatch the pached ones
