### ISSUE TITLE
new player spawn is broken when underground

### ISSUE THREAD

**Issue by dadealus** [MinimallyCorrect/TickThreading#276]
Without TT installed everything functions as intended. With TT installed the new player spawns where they are suppose to then... magically they get pulled to the surface nothing in the logs or errors

i have tried using essentials spawn and homespawnplus both of them work and send the player to the new player spawn location yet 2 or 3 seconds after they are insta ported to the surface in a random location above the new player spawn location.

**Comment by dadealus** [comment]
I will test this today

**Comment by alicheek** [comment]
We some times still get issues with this seems the way its handled is very different from without TT for instance if the server is getting loaded when some one tps to say spawn, the area that they were at will slowly unload and then slowly fall in the void, untill it loads them to the place they have teleported.

Another issue ive noticed is sometimes when the player tps they are submerged  in the block for a second until it realises they shouldnt be in the block.

**Comment by alicheek** [comment]
@nallar 

Just like to say this issue is still a pretty big one (loosing half of my new players with this one) its weird you have the spawn point set with essentials spawn. and so users that type /spawn it seems to work fine for them but when new players go to the spawn point they are either places about 20 blocks way from spawn, places inside a hollow pillar in the spawn building or are glitched out in a wall. ive tested this with an alt char I have by deleting the player data each time to make it like a new player. and almost every time this happens. the weird thing is its fine if the new player just relogs. (issue is most players aren't good enough to even read the welcome text clearly saying if that happens to just relog lol)

**Comment by alicheek** [comment]
Dammit so want to see if the issue is fixed by testing it but got a full server atm, and they will just moan if I do it :P ill tell you as soon as I can wither if its fixed or not, great job with all these fixes though !
