### ISSUE TITLE
TT 1315 - Inconsistent state, a tile entity is in the wrong TickRegion

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#336]
Here is the logs : 

https://gist.github.com/Nohau/5416946

Thanks!

**Comment by Nohau** [comment]
Probaly related to https://github.com/nallar/TickThreading/issues/324

**Comment by Puremin0rez** [comment]
The message is now "gone" in the newer builds, it showed up in my console every-time someone used a Gravity gun to move a tile entity - which makes sense, considering the debug message is telling you exactly that. (tile entity is in the wrong region because a player just moved it)

It's a harmless message as far as I know and shouldn't be visible in the newer builds anymore.

**Comment by Nohau** [comment]
yep just upgraded to 1356 but still getting other errors with chunkloaders it seems.
