### ISSUE TITLE
[TT #1368] [1.4.7 mcpc+ L15] Players going invisible

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#350]
Hey there ive noticed an issue, it seems to be occuring for a while now.

What happens is if you teleport say to an area with other players, sometimes the player that you have teleported near will just disappear like they weren't there. There isnt any error logs but it does happen and can be quite an issue for the players in a pvp situation.

**Comment by Puremin0rez** [comment]
This is also another issue I failed to report. I need to start reporting some of these minor things!

Sometimes when you teleport (via /home, /tp, etc) you will go "invisible" to the other players and even the server.

Odd behavior happens during this time
- You will loose your skin on your client
- You will sometimes be able to "drop" things without it going down in count and produce ghost items
- The server simply messes the hell up for the invisible player (IC2 items don't load there textures and promptly crash the user, etc)

It can be fixed by relogging - but an annoying solution.

**Comment by LunNova** [comment]
If this happens, and you run `/ticks e <dimension id where someone is invisible>` is the reported number of players actually equal to the number of players in that dimension?

**Comment by alicheek** [comment]
ill give that a test

**Comment by alicheek** [comment]
@nallar 

it says there is 36 players when there is actually 44 players on  when i do ticks e

**Comment by Puremin0rez** [comment]
@nallar 

Same as above, it does not show the proper player count.

**Comment by LunNova** [comment]
That sounds like too many players are missing - it's only the count of players in that dimension, not total players. If it was that bad more stuff would be broken :s

**Comment by alicheek** [comment]
well i counted the other dimensions but there is players missing, also ive got an issue with new people spawning, im using essentials spawn (have tried normal bukkit spawning but does the same) and when they join they arent placed where the spawn point actually is , and they  are either stuck in the ground when they come on , its fixed by them re logging but we do loose people because of it .

**Comment by xfloh22** [comment]
thats why u run a creative test server for your people and tell em they can do anything there as long as they report bugs ;)

**Comment by alicheek** [comment]
Still having the same issue. with build 1385

**Comment by alicheek** [comment]
actually seems to be workin now after other testing got another issue though but its a different issue so ill make a new post
