### ISSUE TITLE
[TT1465 - MCPC L20] MFFS not raising shield.

### ISSUE THREAD

**Issue by joey19982** [MinimallyCorrect/TickThreading#402]
No errors or anything, it's just that the blocks to keep you out of an area with MFFS aren't appearing when they should be. Everything else such as actually detecting that you are in the area functions as normal.

**Comment by SuddenTurmoil** [comment]
Ok, so I have an odd conundrum to input for this bug. Currently MFFS shields will not raise on my server. I recently had to restore one of the worlds on my server (FTB ultimate) back to the 30th when the server was running #1444. In that world alone, MFFS shields acted normally, in all other worlds the shields were down. The server was running #1471 at the time. So, did something pollute one of the world files?

**Comment by LunNova** [comment]
If you replace the MFFS blocks in one of the broken worlds, does it start working again?

**Comment by SuddenTurmoil** [comment]
My player tried removing and replacing MFFS blocks to no effect. I just tried it myself replacing all blocks and recreating cards in the event the problem was there. The shield still does not get generated.

**Comment by Nohau** [comment]
Well have good news and bad news.. We managed to get our Force Fields running on my server ever since the bug came to light..but it came at a nasty cost i think..

What we did could be out of pure luck we got it working but maybe nallar might be able to tie some things to gather .. 

So all of our TC3 nodes where slowly disappearing to the point they where starting to get scarce so after talking to our users we decided we will do a TC3 aura regen

So Thaumcraft.cfg changes :+

 B:aura_nodes=true
S:regen_key=1

(Process is still running now over a hour now regenerating new nodes but!)

MFFS Shields are now working and we got this error on startup then destroyed this MFFS and then put a new one back and started working ..

2013-05-06 00:53:22 [SEVERE] [TickThreading] Exception ticking TileEntity c chb.mods.mffs.common.tileentity.TileEntityProjector chb.mods.mffs.common.tileentity.TileEntityProjector@69950df7 x,y,z: -3782, 31, 2122 at x,y,z:-3782,31,2122
 World: Overworld/0
me.nallar.exception.ConcurrencyError: Already replacing
        at me.nallar.tickthreading.collections.CHashMapReplaceClear.clear(CHashMapReplaceClear.java:25)
        at java.util.Collections$SetFromMap.clear(Collections.java:3898)
        at chb.mods.mffs.common.tileentity.TileEntityProjector.calculateField(TileEntityProjector.java:589)
        at chb.mods.mffs.common.tileentity.TileEntityProjector.g(TileEntityProjector.java:515)
        at me.nallar.tickthreading.minecraft.tickregion.TileEntityTickRegion.doTick(TileEntityTickRegion.java:99)
        at me.nallar.tickthreading.minecraft.tickregion.TickRegion.run(TickRegion.java:42)
        at me.nallar.tickthreading.minecraft.ThreadManager$2.run(ThreadManager.java:95)
        at me.nallar.tickthreading.minecraft.ThreadManager$1.run(ThreadManager.java:41)
        at me.nallar.tickthreading.minecraft.ThreadManager$ServerWorkThread.run(ThreadManager.java:167)

What we notice as well the server thinks it is going into a deadlock as soon as you turn on the MFFS and our Deadlock Time is set 120

I do not recommend anyone repeating these steps as it stands now users are randomly disconnecting still and the stuff is still regenerating and depending on your map size this can take a while!

Also users or disconnecting with End of Stream or Buffer Overflow errors right now. 

Will be posting full logs in edit shortly.

**Comment by Nohau** [comment]
Here is the TT LOG

I have zipped up the Forge Log if needed but within that little time it managed to be close to 8MB Text file .

https://gist.github.com/Nohau/5523686

Also it doesn't appear to be not as bad as before and we are able to turn on some MFFS Projectors without it thinking it is in a Deadlock now . 

Some of these are OLD MFFS and New MFFS we and one we just placed down and verified all is working.

We are still watching things closely as the nodes for Thaumcraft regen though.

Thanks,
Nohau

**Comment by Nohau** [comment]
Something else we noticed whenever you change the size of the Projector now you have to pick it up and put it back down and put in the new cards then.

**Comment by cjm721** [comment]
Just updated to 1552 and my shield was there then I teleported to my base but after i turned it off then back on it never came back up.

Also the shield is dropping very slowly, don't really mind it going slowly as less lag (64 radius sphere), but wonder if it has something to do with it.

going to try nallar's new fix now (github should give a warning if someone posts while your typing).

**Comment by cjm721** [comment]
Tried both new and old projectors and none seem to work on 1554

**Comment by Nohau** [comment]
Also something we noticed is if there is bed rock near the MFFS it bugs out and doesn't create the shield correctly on 1547 or not at all . We had to ensure we where not even near bedrock and the shield came up.  

We had a house that had a bedrock foundation and how we found this issue (this was done in creative mode)

Thaumcraft is still doing a world gen on all the nodes still this is taking forever but no real side effects besides lots of errors from essentials & prism but it is related to https://github.com/nallar/TickThreading/issues/454 .

**Comment by Nohau** [comment]
I upgraded to 1554 and it not longer works :(

**Comment by Nohau** [comment]
Downgraded and they started working again.

**Comment by inferno771** [comment]
Nohau, were you able to find out the latest version that worked with MFFS without breaking the fields?

**Comment by inferno771** [comment]
It would seem build 1448 is where the fields were broken, all versions beyond that up to today (build 1610) no longer allow mffs to raise it's fields.

**Comment by cjm721** [comment]
Had no effect 
MCPC 23
TT 1614

**Comment by SuddenTurmoil** [comment]
It appears to have had no effect on the MFFS items on my server either. Running vanilla FTB Ultimate 1.0.1. Super happy you are working on this issue though! Thanks!

**Comment by CappyT** [comment]
Same on MCPC+ L15 - TT 1626

MFFS Turns on, no shield and no error in console. Shields turned on before TT are still okay.

**Comment by Nohau** [comment]
I have verified with Ultimate 1.1.2  and TT 1748 MFFS is working again.
