### ISSUE TITLE
TT1461 / MCPC L15 Deadlock

### ISSUE THREAD

**Issue by Nohau** [MinimallyCorrect/TickThreading#415]
Here is the gist : https://gist.github.com/Nohau/5486186

Looks like we where also experiencing https://github.com/nallar/TickThreading/issues/410 So I have upgraded to 1471

I am starting to wondering if it is possible that some of these deadlocks may becuase my age worlds is on slower drives then my overworld causing a write build up.. 

i.e Age is on RAID drives in overworld is on SSD .

Thanks,

**Comment by cjm721** [comment]
Believe I am the same or very similar issue.

MCPC 19 TT 1484 
FTB Ultimate Pack 1.01
Occurs also on Direwolf20 Pack

From what I have been able to deduce from the occurrences on my server I have gotten this:

1) Due to chunks loading at location of player login, ie if I go there from another account that is already logged in and then player1 logs in no deadlock.

2) If I change where the player will login (using essentials / world player file) there is no crash when they come on.
- Sub note about the deadlock I link is that player is logging in age 29 while TT logs say issue is in age 24 (player has not gotten back to me if he has a chunk-loader there of which I have them only on if the owning player is online)

3) All the lua stacktraces are from ComputerCraft, or at least only thing I know that uses lua API in ultimate pack and the huge amount of threads relating to them corresponds to the large use of turtles on my server.

http://pastebin.com/nrm8mqgt

**Comment by LunNova** [comment]
An explosion took too long, increase the deadlock detector time.

**Comment by LunNova** [comment]
@cjm721 

Make a new issue. Also, 99% of the time CC's lua threads aren't related at all. Look at the bottom of the report, see the "definitely deadlocked" bit.
