### ISSUE TITLE
Crash on login when players are sharing base with chunkloaders nearby 1599

### ISSUE THREAD

**Issue by Maximuscr31** [MinimallyCorrect/TickThreading#485]
I am having an issue when any players that share a base login. It doesn't have to be both. If player 1 logs in and player 1 and 2 have chunkloaders side by side then it crashes. After the reboot player 1 can log in. This happens every so often during the day. Breaking one  of the two chunkloaders side by side seems to fix the issue. Without TT it doesn't do this. Server log just says server deadlocks and reboots with no error. I am using 1599 and MCPC L22. I am not sure if its a TT issue or a setting conflicting with TT. I also searched and found no relevant tickets. 
Thanks
Brandon

Here are my configs
Bukkit :mcpc:
  connection-logging: false
  dump-materials: false
  infinite-water-source: true
  flowing-lava-decay: true
  load-chunk-on-request: false

ChickenChunks
# Per player chunk limiting. Values ignored if 0.
# Simply add <username>=<value>

players
{
    #Forge gives everyone 12500 by default
    DEFAULT=5000
    #For server op's only.
    OP=5000
}
# If set to false, players will have to be logged in for their chunkloaders to work.
# Simply add <username>=<true|false>

allowoffline
{
    DEFAULT=true
    OP=true
}
# Set to false to deny a player access to the chunk viewer

allowchunkviewer
{
    DEFAULT=true
    OP=true
}
# The number of minutes since last login within which chunks from a player will remain active, 0 for infinite.

awayTimeout=5

block.id=243
# The number of ticks to wait between attempting to unload orphaned chunks

cleanuptime=0
# The maximum number of chunks per chunkloader

maxchunks=400
# Set to false to disable the automatic reloading of mystcraft dimensions on server restart

reload-dimensions=false

and tickthreading:
# Configuration file
###### 
# general
###### 

general {
    # Whether worlds should be allowed to unload.
    B:allowWorldUnloading=false

```
# Whether to kick players for detected cheating
B:antiCheatKick=false

# Whether to notify admins if TT anti-cheat detects cheating
B:antiCheatNotify=false

# Number of unloaded chunks to keep cached. Replacement for Forge's dormant chunk cache, which tends to break. Minimum size of 100
I:chunkCacheSize=2000

# Interval between chunk garbage collections in ticks
I:chunkGCInterval=1200

# Whether to clean worlds on unload - this should fix some memory leaks due to mods holding on to world objects
B:cleanWorlds=false

# Whether network ticks should be ran in a separate thread from the main minecraft thread. This is likely to be very buggy, especially with mods doing custom networking such as IC2!
B:concurrentNetworkTicks=false

# The time(seconds) of being frozen which will trigger the DeadLockDetector.
I:deadLockTime=45

# List of dimensions not to enable fast spawning in.
I:disableFastMobSpawningDimensions <
    -1
 >

# Name of the command to be used for profiling reports.
S:dumpCommandName=dump

# Whether to enable warning if there are severe known compatibility issues with the current TT build you are using and your installed mods. Highly recommend leaving this enabled, if you disable it chances are you'll get users experiencing these issues annoying mod authors, which I really don't want to happen.
B:enableBugWarningMessage=false

# If enabled, TT's alternative mob spawning implementation will be used.
B:enableFastMobSpawning=true

# If the server should shut down when a deadlock is detected
B:exitOnDeadlock=true

# The message to be displayed if a deadlock is detected. (Only sent if exitOnDeadlock is on)
S:messageDeadlockDetected=The server appears to have frozen and will restart soon if it does not recover. :(

# The message to be displayed if the server recovers from an apparent deadlock. (Only sent if exitOnDeadlock is on)
S:messageDeadlockRecovered=The server has recovered and will not need to restart. :)

# The message to be displayed when the server attempts to save and stop after a deadlock. (Only sent if exitOnDeadlock is on)
S:messageDeadlockSavingExiting=The server is saving the world and restarting - be right back!

# Name of the command to be used for profiling reports.
S:profileCommandName=profile

# width/length of tick regions, specified in blocks.
I:regionSize=16

# If a player must be opped to use /dump
B:requireOpsForDumpCommand=true

# If a player must be opped to use /profile
B:requireOpsForProfileCommand=true

# If a player must be opped to use /ticks
B:requireOpsForTicksCommand=true

# Time between auto-saves, in ticks.
I:saveInterval=180

# Whether chunks within 200 blocks of world spawn points should always be loaded.
B:shouldLoadSpawn=false

# TPS the server should try to run at.
I:targetTPS=20

# number of threads to use to tick. 0 = automatic
I:tickThreads=0

# Name of the command to be used for performance stats. Defaults to ticks.
S:ticksCommandName=ticks

# Name of the command to be used for TPS reports.
S:tpsCommandName=tps

# Allows tick rate to vary per region so that each region uses at most 50ms on average per tick.
B:variableRegionTickRate=true

# Whether we should wait until all Tile/Entity tick threads are finished before moving on with world tick. False = experimental, but may improve performance.
B:waitForEntityTickCompletion=true
```

}

**Comment by LunNova** [comment]
You've given all the files I don't need :P

I need either the TickThreading log from your TT logs folder, or a console log.

**Comment by Meatnog** [comment]
Here's the console (for Max):

12.05 09:57:04 [Server] SEVERE Failed to recover from the deadlock.
12.05 09:57:04 [Multicraft] Skipped 3471 lines due to rate limit (30/s)
12.05 09:56:58 [Server] INFO Number of locked synchronizers = 1
12.05 09:56:58 [Server] INFO at me.nallar.tickthreading.util.FakeServerThread.run(FakeServerThread.java:16)
12.05 09:56:58 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
12.05 09:56:58 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
12.05 09:56:58 [Server] INFO at me.nallar.patched.storage.ThreadedChunkProvider$ChunkLoadRunnable.run(ThreadedChunkProvider.java:840)
12.05 09:56:58 [Server] INFO at im.getChunkAt(ThreadedChunkProvider.java:464)
12.05 09:56:58 [Server] INFO -  locked me.nallar.tickthreading.util.concurrent.NativeMutex@680f844c
12.05 09:56:58 [Server] INFO -  locked java.util.concurrent.atomic.AtomicInteger@76114612
12.05 09:56:58 [Server] INFO at im.getChunkAtInternal(ThreadedChunkProvider.java:554)
12.05 09:56:58 [Server] INFO at zz.threadUnsafeChunkLoad(Chunk.java:175)
12.05 09:56:58 [Server] INFO at yc.a(World.java:585)
12.05 09:56:58 [Server] INFO at codechicken.chunkloader.TileChunkLoaderBase.s(TileChunkLoaderBase.java:40)
12.05 09:56:58 [Server] INFO at codechicken.chunkloader.TileChunkLoader.activate(TileChunkLoader.java:115)
12.05 09:56:58 [Server] INFO at codechicken.chunkloader.TileChunkLoaderBase.activate(TileChunkLoaderBase.java:126)
12.05 09:56:58 [Server] INFO at codechicken.chunkloader.ChunkLoaderManager.addChunkLoader(ChunkLoaderManager.java:698)
12.05 09:56:58 [Server] INFO at codechicken.chunkloader.ChunkLoaderManager$ChunkLoaderOrganiser.addChunkLoader(ChunkLoaderManager.java:187)
12.05 09:56:58 [Server] INFO at codechicken.chunkloader.ChunkLoaderManager$ChunkLoaderOrganiser.forceChunks(ChunkLoaderManager.java:240)
12.05 09:56:58 [Server] INFO at codechicken.chunkloader.ChunkLoaderManager$TicketManager.addChunk(ChunkLoaderManager.java:115)
12.05 09:56:58 [Server] INFO at net.minecraftforge.common.ForgeChunkManager.forceChunk(ForgeChunkManager.java:62)
12.05 09:56:58 [Server] INFO at net.minecraftforge.event.EventBus.post(EventBus.java:103)
12.05 09:56:58 [Server] INFO at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
12.05 09:56:58 [Server] INFO at net.minecraftforge.event.ASMEventHandler_162_ChunkLoaderEventHandler_onChunkForce_ForceChunkEvent.invoke(.dynamic)
12.05 09:56:58 [Server] INFO -  blocked on java.lang.Object@52b6cef3
12.05 09:56:58 [Server] INFO at codechicken.chunkloader.ChunkLoaderEventHandler.onChunkForce(ChunkLoaderEventHandler.java)
12.05 09:56:58 [Server] INFO "Async ChunkLoader" BLOCKED on java.lang.Object@52b6cef3 owned by "World Tick - 4" Id=211
12.05 09:56:58 [Server] INFO Waiting ThreadManagers: World Tick
12.05 09:56:58 [Server] INFO Last tick 46s ago.
12.05 09:56:58 [Server] SEVERE The server appears to have deadlocked.

**Comment by LunNova** [comment]
> `12.05 09:57:04 [Multicraft] Skipped 3471 lines due to rate limit (30/s)`

Multicraft is very helpfully ignoring TT's logging.

Could you paste a copy of the log in TT's log folder, maybe also turn off multicraft's rate limiting?

**Comment by Maximuscr31** [comment]
https://drive.google.com/folderview?id=0B5yKfXm1PkuLLTJTRExnSmRNbWM&usp=sharing
That will have the console log in full. It shouldn't skip anything in it. I have it set to trim it from console view, not from the actual log. Also I posted all 5 of tickthreadings logs as well. I was really hoping it would be another one of those "you need to change x setting" . Sorry for not posting them earlier. Also thanks for the help Nallar.

**Comment by Maximuscr31** [comment]
Also when Meatnog logged in he believes he had broken all chunkloaders his partners had. He still had  his own and it still crashed so I might be incorrect in the common variable.

**Comment by Maximuscr31** [comment]
Here is a TT log from where Meatnog logged in when the server had been up and fine for several hours. Logs in, he gets in, it deadlocks immediately. We are now on MCPC L27 and TT1603

http://pastebin.com/51P8QyLg

**Comment by Maximuscr31** [comment]
Since updating to mcpc 27 and TT1610 and Ultimate v1.1.0 I have not had any instances of this yet. Here is to hoping it is resolved.

**Comment by Meatnog** [comment]
Nope, it is not resolved.   Happens pretty reliably still.

**Comment by Maximuscr31** [comment]
If meatnog deletes his chunkloaders before log off it never happens. If he doesn't and the server has been up any amount of time it dead locks. It only happens to a few players. It is really odd.

**Comment by LunNova** [comment]
I need to change the way I'm patching ChickenChunks, a bit of a pain to fix but will get it done at some point.

**Comment by LunNova** [comment]
This is now fixed, implemented the change described in the previous comment.
