### ISSUE TITLE
Disabling Loading Spawn chunks not actually working? - Build 437

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#56]
I have the option set to false but it appears as if it's not actually working, unless the /tps command provides invalid stats.

I have it set to false and all of the worlds with 0.2% are the ones without any players in them, but if the spawn chunks were disabled, why would there still be entities and load on the worlds?

http://i.imgur.com/8onnq.png

All chunk loaders from various mods are disabled and forced disabled via forgechunkloading.cfg

**Comment by LunNova** [comment]
There's a small load because the worlds still do some non-entity/chunk related updates - eg: time of day.

Mystcraft should unload them when empty, if that's what you're using, and it's also surprising that there is one loaded tile entity in one of the empty worlds - maybe a single chunk directly at spawn is being loaded?

**Comment by Puremin0rez** [comment]
It might be a single chunk, but if I'm right, I'm pretty positive there isn't any tile entities in the single chunk of most of the worlds.

**Comment by Puremin0rez** [comment]
Hmm, well, according to aPerf, all the chunks etc are disabled in those worlds - so I guess we're fine :)
