### ISSUE TITLE
BC Quarries not obeying forgeChunkLoading.cfg?

### ISSUE THREAD

**Issue by Puremin0rez** [MinimallyCorrect/TickThreading#67]
Not sure if this is a TT bug - I don't have time to test :\

My forgeChunkLoading.cfg looks like this:
http://pastebin.com/jsnQ3zbB

Which is supposedly supposed to disable all chunk loading features from mods, however, something strange is happening with BC Quarries.

I get a message in console saying
"2013-01-18 06:41:01 [INFO] [ForgeModLoader] The mod BuildCraft|Factory has attem
pted to allocate a chunkloading ticket beyond it's currently allocated maximum :
 0"

I get a message in chat saying
"Chunk loading is disabled which means the quarry at x,x,x will not work"

but then right after It says it'll keep x chunks loaded and works perfectly fine.

I can check with aPerf or /tps and it'll show that there are 2 chunks loaded and 2 of them are forced - being the chunks the quarry said it would keep loaded.

I have a feeling that TT is "overriding" this chunk loading limit or something similar.

I come back and yes, the quarry ran the entire time I was gone.

Hope someone can chime in :)

**Comment by LunNova** [comment]
Make an issue with forge.

http://i.imgur.com/xqTlB.png - As you can see there, it warns about the mod, then returns null and gives no ticket - however, the second time a ticket is requested, it just gives a ticket because it's already warned.

Obviously it should return null every time if it's over the limit, not only when it has not yet warned.
